#伤害文本会在多久之后消失? 20Tick=1s
RunTick: '20'

Rand:
  #最大偏移量
  RandMax: '0.5'
  #最小偏移量
  RandMin: '-0.5'
  #文本上浮速度
  TextRise: '0.1'

#暴击时显示的文字
CritText: '&e&l&n&oCrit!&r '
#暴击时的音效
CritSound: 'ENTITY_IRON_GOLEM_DAMAGE'
#生命恢复时显示的文字
RegainHealthText: '&f&l&o'
#生命减少时显示的文字
LoseHealthText: '&f&l&o&d&l&o-'

DamagType:
  #排序名字,可以自由添加.
  Damage1:
    #AP中的属性名称
    DamageName: '本位伤害'
    #读取APE造成伤害时赋予伤害量的属性
    DamageValue: '本位伤害全息值'
    #显示在伤害数字前的文本
    DamageText: '&9&l&o'
  Damage2:
    DamageName: '变动伤害'
    DamageValue: '变动伤害全息值'
    DamageText: '&a&l&o'
  Damage3:
    DamageName: '固定伤害'
    DamageValue: '固定伤害全息值'
    DamageText: '&c&l&o'